language: node_js
node_js:
  - "9.11.1"
dist: xenial
sudo: true

branches:
  only:
      - master
      - develop
addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
  - cp src/environments/environment.docker.ts src/environments/environment.ts
  - ng lint
  - ng test --watch=false