language: node_js
node_js:
  - "10.4.1"
dist: xenial
sudo: true

addons:
  chrome: stable

branches:
  only:
      - master
      - develop

cache:
  directories:
  - node_modules
  
before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false
  
	