language: node_js
node_js:
  - "11.2.0"
dist: xenial
sudo: true

branches:
  only:
      - master
      - develop
addons:
  chrome: stable
cache:
  directories:
  - node_modules
  yarn: true

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false
